import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import {PlaybackBar} from "./PlaybackBar";
import { getDb } from "@/lib/db";
import { get_id } from "@/actions/login";
import { PlaybackContextProvider } from "./playbackContextProvider";
import { SideBar } from "./sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const db = getDb()
  const user_id = await get_id()

  const randomSongs = await db
  .selectFrom("songs")
  .innerJoin("albums", "songs.album_id" ,"albums.id")
  .innerJoin("authors","albums.author_id", "authors.id")
  .select(['songs.id','songs.name', 'authors.name as author','songs.duration'])
  .limit(10)
  .execute();

    const likedSongIds =
    user_id != null
      ? await db
          .selectFrom("user_liked_songs")
          .where("user_id", "=", user_id)
          .select("song_id")
          .execute()
      : null;

  const playlists = await db
    .selectFrom("playlists")
    .selectAll()
    .where("user_id", "=", user_id)
    .execute();

  return (
    <html lang="en">
              <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">

      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">


        <PlaybackContextProvider initialSongs={randomSongs}>
          <div className="pb-4">{children}</div>
          
          <div className="fixed top-0 left-0 right-0">
            <NavBar />
          </div>
          <div className="fixed top-0 bottom-0 right-0 pt-20 w-40">
            <SideBar />
          </div>

          {likedSongIds != null && playlists != null ? (
            <div className="fixed h-24 bg-base-100 bottom-0 left-0 right-0 inset-shadow-sm">
              <PlaybackBar
                initialSongs={randomSongs}
                likedSongIds={likedSongIds.map((row) => row.song_id)}
                playlists={playlists}
              />
            </div>
          ) : null}
        </PlaybackContextProvider>
        
      
      </main>
      

      </div>
      </body>

      
    </html>
  );
}
